name: Go CI/CD Pipeline with Docker

on:
  push:
    branches:
      - master # Запуск только для ветки master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build Docker Image
    runs-on: ubuntu-latest

    steps:
      # Проверяем код из репозитория
      - name: Checkout code
        uses: actions/checkout@v4

      # Логин в Docker Hub (если нужно)
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Строим Docker-образ
      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/my-go-app:${{ github.sha }} .

      # Загружаем образ в Docker Hub
      - name: Push Docker image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/my-go-app:${{ github.sha }}

  test:
    name: Test
    runs-on: ubuntu-latest
    needs: build # Запускается после успешной сборки

    steps:
      # Проверяем код из репозитория
      - name: Checkout code
        uses: actions/checkout@v4

      # Устанавливаем Go
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.20

      # Запускаем тесты
      - name: Run tests
        run: |
           go test ./... -v
#          go test ./... -v -coverprofile=coverage.out
#          go tool cover -func=coverage.out

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: test # Запускается после тестов

    steps:
      # Проверяем код из репозитория
      - name: Checkout code
        uses: actions/checkout@v4

      # Настраиваем SSH для деплоя
      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.DEPLOY_HOST }} >> ~/.ssh/known_hosts

      # Деплой на сервер
      - name: Deploy Docker container
        run: |
          ssh ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_HOST }} \
            "docker pull ${{ secrets.DOCKER_USERNAME }}/my-go-app:${{ github.sha }} && \
            docker run -d -p 8080:8080 ${{ secrets.DOCKER_USERNAME }}/my-go-app:${{ github.sha }}"
